runner:
  # Number of concurrent jobs
  capacity: 1
  file: .runner
  timeout: 3h
  insecure: false
  fetch_timeout: 5s
  fetch_interval: 2s
  labels:
    - linux/amd64
    - crypto
    - hil
    - stm32

cache:
  enabled: true
  dir: /cache
  ttl: 7 days

log:
  level: info

network:
  ipv6: false
